### ISSUE TITLE
UKHPI logging inadequate

### ISSUE THREAD

**Issue by andrew-pickin-epi** [epimorphics/hmlr-linked-data#104]
- [x] DEBUG level logs seen in production.
- [x] Errors reported as INFO
- [x] Inconsistent units for `duration` field. See also proxy logging.
- [x] Inconsistent use of status: this should be http status code. Not text (see below).
- [ ] Path arriving at proxy not reflected in ukhpi.
  eg. Proxy logs `/app/ukhpi/browse/edit?lang=en&st%5B%5D=cas&st%5B%5D=det&st%5B%5D=exi&st%5B%5D=foo&st%5B%5D=mor&st%5B%5D=new&st%5B%5D=sem&st%5B%5D=ter&thm%5B%5D=property_status&thm%5B%5D=volume`
  uphpi for equivalent request id `/app/ukhpi/browse/edit` all search information is lost.
- [ ] rail log structure. Does this add any value?
-[  ] `[Transport] Sending envelope with items [sessions]  to Sentry`:  Does this have any value? What do the `[]` indicate, is there any way to reconcile with Sentry logs?
- [ ] Where are the number of rows returned?

Consider the following: `{"level":"INFO","ts":"2022-09-20T09:58:19.927Z","request_id":"YymOuz4-ITD2WkiKjV2Q7QAAANI","rails":{"environment":"production","url":"http://data-api:8080/landregistry/id/ukhpi","message":"Failed to read from http://data-api:8080/landregistry/id/ukhpi: 503"},"status":"service exception","duration":0.030520931}`

[Most of] the actual request has been lost. 
A service exception like this should result in Level: ERROR, Status: 503.

I'm inclined to think this should be one log entry per external request, consisting of (but not limited to), request is, query, status, rows and duration in unit as per proxy (See %D https://httpd.apache.org/docs/2.4/mod/mod_log_config.html)

**Comment by andrew-pickin-epi** [comment]
Version 1.6.2_00b4500_00000058

###  Still have truncated path. 
eg Proxy logs path as
```
log_path | /app/ukhpi/browse?lang=en&st%5B%5D=all&st%5B%5D=cas&st%5B%5D=exi&st%5B%5D=fla&st%5B%5D=ftb&st%5B%5D=mor&st%5B%5D=new&st%5B%5D=ter&thm%5B%5D=buyer_status&thm%5B%5D=funding_status&thm%5B%5D=property_status&thm%5B%5D=volume
```
But ukhpi truncates 
```
log_path | /app/ukhpi/browse
```

### Still have DEBUG events adding nothing of value. 
```
{"ts":"2023-06-06T08:52:27.397Z","level":"DEBUG","request_id":"ZH7zy_T-tGryrW9Zn-khSQAAAJU","message":"query took 46894 μs"}
```

### Info messages too brief
```
{"ts":"2023-06-06T08:52:27.395Z","level":"INFO","request_id":"ZH7zy_T-tGryrW9Zn-khSQAAAJU","status":200,"duration":45113}
```
Which query? What actually took this long? why doesn't is correspond with the previous debug?

### Useful detail concealed within debug
```
{"ts":"2023-06-06T08:52:27.350Z","level":"DEBUG","request_id":"ZH7zy_T-tGryrW9Zn-khSQAAAJU","message":"About to perform API query: {\"@and\":[{\"ukhpi:refMonth\":{\"@ge\":{\"@value\":\"2022-05\",\"@type\":\"http://www.w3.org/2001/XMLSchema#gYearMonth\"}}},{\"ukhpi:refMonth\":{\"@le\":{\"@value\":\"2023-05\",\"@type\":\"http://www.w3.org/2001/XMLSchema#gYearMonth\"}}},{\"ukhpi:refRegion\":{\"@eq\":{\"@id\":\"http://landregistry.data.gov.uk/id/region/united-kingdom\"}}}],\"@sort\":[{\"@up\":\"ukhpi:refMonth\"}]}"}
```
The is not "About to" the time stamp suggests this has happened. 
This is the event to are concerned about.
Log as INFO, what the query is, where is was requested, how long it took, what the status was, what was returned etc.

**Comment by jonrandahl** [comment]
@andrew-pickin-epi just adding these here as checkboxes to return to:

## Log as a minimum:

- [ ] as INFO if successful, ERROR if not
- [ ] what the query is
- [ ] where it was requested
- [ ] how long it took
- [ ] what the status was
- [ ] what was returned (number of rows or byte count etc)
- [ ] high level text message

**Comment by jonrandahl** [comment]
![CleanShot 2023-06-29 at 12 23 25](https://github.com/epimorphics/hmlr-linked-data/assets/39102/7d52bd0f-00a6-4d54-a204-218dff3da621)

@andrew-pickin-epi, I think we need to make a decision on what is acceptable due to the manner  of which the Ruby on Rails framework reports events?

I've been in to both Kibana and my local logs to try to reconcile the "missing" fields you pointed out and have determined that it would take a lot longer to resolve trying to “merge” the corresponding logs into some semblance of a “single” log, alongside including the same fields in every log, as they are indeed different shapes for each log message. 

I've included local logs from my testing which highlight the differences and similarities between what was received from rails and parsed by the logger gem for reference:

```
received log: Current DsAPI query: {"@json_mode":"compact","@and":[{"ppd:propertyAddress":{"@search":{"@value":"( Rose AND Cottage )","@property":"lrcommon:paon","@limit":3000000}}},{"ppd:propertyAddress":{"@search":{"@value":"( Plymouth )","@property":"lrcommon:town","@limit":3000000}}},{"ppd:pricePaid":{"@ge":100000}},{"ppd:pricePaid":{"@le":300000}}]}
transformed log: {"ts":"2023-06-29T12:02:17.687Z","level":"DEBUG","request_id":"fed9587a-12bd-4e1d-8d92-9625580a13fa","message":"Current DsAPI query: {\"@json_mode\":\"compact\",\"@and\":[{\"ppd:propertyAddress\":{\"@search\":{\"@value\":\"( Rose AND Cottage )\",\"@property\":\"lrcommon:paon\",\"@limit\":3000000}}},{\"ppd:propertyAddress\":{\"@search\":{\"@value\":\"( Plymouth )\",\"@property\":\"lrcommon:town\",\"@limit\":3000000}}},{\"ppd:pricePaid\":{\"@ge\":100000}},{\"ppd:pricePaid\":{\"@le\":300000}}]}"}

received log: {"request_url"=>"http://localhost:8888/landregistry/id/ppd?maxeq-pricePaid=300000&mineq-pricePaid=100000&search-paon=Rose+Cottage&search-town=Plymouth&searchPath=propertyAddress", "status"=>200, "duration"=>418421, "message"=>"Completed Data Services API request, time taken 418421 μs"}
transformed log: {"ts":"2023-06-29T12:02:18.106Z","level":"INFO","request_id":"fed9587a-12bd-4e1d-8d92-9625580a13fa","request_url":"http://localhost:8888/landregistry/id/ppd?maxeq-pricePaid=300000\u0026mineq-pricePaid=100000\u0026search-paon=Rose+Cottage\u0026search-town=Plymouth\u0026searchPath=propertyAddress","status":200,"duration":418421,"message":"Completed Data Services API request, time taken 418421 μs"}

received log: {"duration"=>2040548, "request_id"=>nil, "forwarded_for"=>nil, "path"=>"/search", "query_string"=>"et%5B%5D=lrcommon%3Afreehold&et%5B%5D=lrcommon%3Aleasehold&limit=all&max_price=300000&min_price=100000&nb%5B%5D=true&nb%5B%5D=false&paon=Rose+Cottage&ptype%5B%5D=lrcommon%3Adetached&ptype%5B%5D=lrcommon%3Asemi-detached&ptype%5B%5D=lrcommon%3Aterraced&ptype%5B%5D=lrcommon%3Aflat-maisonette&ptype%5B%5D=lrcommon%3AotherPropertyType&tc%5B%5D=ppd%3AstandardPricePaidTransaction&tc%5B%5D=ppd%3AadditionalPricePaidTransaction&town=Plymouth", "user_agent"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36", "accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "body"=>nil, "method"=>"GET", "status"=>200, "message"=>"OK"}
transformed log: {"ts":"2023-06-29T12:02:19.713Z","level":"INFO","request_id":"fed9587a-12bd-4e1d-8d92-9625580a13fa","duration":2040548,"path":"/search","query_string":"et%5B%5D=lrcommon%3Afreehold\u0026et%5B%5D=lrcommon%3Aleasehold\u0026limit=all\u0026max_price=300000\u0026min_price=100000\u0026nb%5B%5D=true\u0026nb%5B%5D=false\u0026paon=Rose+Cottage\u0026ptype%5B%5D=lrcommon%3Adetached\u0026ptype%5B%5D=lrcommon%3Asemi-detached\u0026ptype%5B%5D=lrcommon%3Aterraced\u0026ptype%5B%5D=lrcommon%3Aflat-maisonette\u0026ptype%5B%5D=lrcommon%3AotherPropertyType\u0026tc%5B%5D=ppd%3AstandardPricePaidTransaction\u0026tc%5B%5D=ppd%3AadditionalPricePaidTransaction\u0026town=Plymouth","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","method":"GET","status":200,"message":"OK"}

received log: {"method"=>"GET", "path"=>"/search", "format"=>"html", "controller"=>"SearchController", "action"=>"index", "status"=>200, "duration"=>2041.18, "view"=>1596.07, "exception"=>nil, "exception_object"=>nil}
transformed log: {"ts":"2023-06-29T12:02:19.714Z","level":"INFO","request_id":"fed9587a-12bd-4e1d-8d92-9625580a13fa","method":"GET","path":"/search","status":200,"duration":2041180}

received log: {"duration"=>666616, "request_id"=>nil, "forwarded_for"=>nil, "path"=>"/", "query_string"=>"", "user_agent"=>"curl/7.88.1", "accept"=>"*/*", "body"=>nil, "method"=>"HEAD", "status"=>200, "message"=>"OK"}
transformed log: {"ts":"2023-06-29T12:12:30.542Z","level":"INFO","request_id":"3ea83d48-778b-4019-9d08-ea4a54d2fbd6","duration":666616,"path":"/","query_string":"","user_agent":"curl/7.88.1","accept":"*/*","method":"HEAD","status":200,"message":"OK"}

received log: {"method"=>"HEAD", "path"=>"/", "format"=>"*/*", "controller"=>"PpdController", "action"=>"index", "status"=>200, "duration"=>668.9, "view"=>651.45, "exception"=>nil, "exception_object"=>nil}
transformed log: {"ts":"2023-06-29T12:12:30.543Z","level":"INFO","request_id":"3ea83d48-778b-4019-9d08-ea4a54d2fbd6","method":"HEAD","path":"/","status":200,"duration":668900}
```

**Comment by tomguilbert** [comment]
@andrew-pickin-epi @jonrandahl and I I have agreed that as much as is possible within the constraints of rails has been done here and this can now be closed.
