### ISSUE TITLE
UKHPI service interuption not handled well

### ISSUE THREAD

**Issue by andrew-pickin-epi** [epimorphics/hmlr-linked-data#105]
Fuseki is down (maybe restarting), ukhpi gets 503. This is reflected back to proxy as 400. 
What the UX is I can't say but passing back a 400(bad request) can't be correct.

**Comment by tomguilbert** [comment]
App should report 500 error to the client with a meaningful message. Logging should maintain 500 error (not change to 400).

**Comment by tomguilbert** [comment]
@jonrandahl has done this one so I'm closing
