### ISSUE TITLE
Review CSRF settings for ppd-explorer

### ISSUE THREAD

**Issue by der** [epimorphics/hmlr-linked-data#107]
The ppd-explorer runs CSRF protection [using](https://github.com/epimorphics/ppd-explorer/blob/08848fbc72f07b97cc4f23669ed86aadc1086a0d/app/controllers/application_controller.rb#L7):

```
  protect_from_forgery with: :exception
```

This means that an attempt to call PPD using a POST request, other than as part of a valid browser session with the matching CSRF `authenticity_token`, will throw and internal exception which is not caught anywhere are results in a 500 error return. It may also be the explanation for #103 .

To enable load testing we have changed this to:

```
protect_from_forgery with: :null_session
```

which allows the request to continue processing but outside any session. 

In effect this is allowing PPD to be used as an API. But that is already possible since PPD does support GET format requests which it uses for deep linked (e.g. in the share view action) so this does not seem like an increased exposure.

Review whether to leave this CSRF setting (and clean up the comment) or revert to the prior behaviour after load testing is complete.
/cc @jonrandahl

**Comment by jonrandahl** [comment]
as discussed @der and I have agreed to leave the load testing changes in place and act as the PPD explorer is more of an API to be monitored for differences in any reports and revised again if needed.

Back to you @der!

**Comment by der** [comment]
Thanks @jonrandahl in that case, I think review is done and will close this ticket.
