### ISSUE TITLE
Incorrect response code from PPD

### ISSUE THREAD

**Issue by der** [epimorphics/hmlr-linked-data#108]
This is an illegal query to PPD, probably generated by someone attempting to use PPD as an API. The min price is 1.0 whereas it should be a float:

```
/app/ppd/search?county=horley&district=smallfield&et%5B%5D=lrcommon%3Afreehold&et%5B%5D=lrcommon%3Aleasehold&limit=100&locality=horley&max_date=2022-08-27&min_date=2000-01-27&min_price=1.00&nb%5B%5D=false&paon=23&postcode=rh6+9qr&ptype%5B%5D=lrcommon%3Adetached&ptype%5B%5D=lrcommon%3Asemi-detached&ptype%5B%5D=lrcommon%3AotherPropertyType&street=kings+mead&tc%5B%5D=ppd%3AstandardPricePaidTransaction&tc%5B%5D=ppd%3AadditionalPricePaidTransaction
```

The data-api returns a 400 for this case.

However, PPD returns a 500 error response.

**Comment by der** [comment]
This is partly obsoleted by #110 but when there are 400 responses from the API that should probably return a 400 from the app as well.

**Comment by jonrandahl** [comment]
This has been resolved to pass in the status value from the error itself instead of a blanket 500 if it's not a specific type of error:

```ruby
  rescue StandardError => e
    e = e.cause || e
    status = case e
             when MalformedSearchError, ArgumentError
               400
             else
               e.status || 500
             end
```
PS. no, ruby does not have a null coalescing operator or I would have used that! ;-)

**Comment by der** [comment]
Fixed.
