### ISSUE TITLE
PPD: Improve APIServiceException on 4XX

### ISSUE THREAD

**Issue by der** [epimorphics/hmlr-linked-data#109]
When a user treats the PPD application as an API they can supply illegal query parameters.

This results in the data-api correctly returning a 400 error.

This in turn generates two alerts via the PPD metrics as shown in epimorphics/hmlr-ansible-deployment#147

Given the usage levels for HMLR I don't think we want alerts on 4XX errors.

Of the two alerts the `Warning: APIStatus` can be dealt with in the ops infrastructure by only alerting on 5XX errors.

However, the `APIServiceException` can be suppressed in the ops infrastructure for this case without suppressing it for everything.

Suggest that an API 400 error should not raise `APIServiceException` or at least not in cases like this.

**Comment by der** [comment]
Duplicate or near duplicate of #108

**Comment by jonrandahl** [comment]
@der this might also be resolved with the updates in #103 as well as the logging updates in [json-rails-logger](https://github.com/epimorphics/json-rails-logger) and the [data_services_api](https://github.com/epimorphics/data_services_api) gems once released.

**Comment by tomguilbert** [comment]
@der We're just reviewing the remaining FE logging tickets and wondered if this is now resolved as per @jonrandahl 's comment above - can you please check?

**Comment by der** [comment]
Don't know how I can check. The links above are to the whole of the logger and services api gem, don't think it makes sense for me to try to read through all that code to see if I can work out if it's covered.

And I don't have a simple test case because the most common one was decimals #110 which was dealt differently.

If there's been specific changes to no longer increment error metrics for 400 errors from the API then I'm happy to accept that  assertion and close this.

**Comment by tomguilbert** [comment]
@der - this is still being worked on by @jonrandahl via #104 and #105 so putting back into 'in progress' and will report back once those are done

**Comment by tomguilbert** [comment]
@jonrandahl has done this
