### ISSUE TITLE
hmlr_elda time_taken changed to duration

### ISSUE THREAD

**Issue by andrew-pickin-epi** [epimorphics/hmlr-linked-data#112]
Bring into line the logging of elapsed time with other elements to be logged as `duration`, in microseconds as an integer.

**Comment by der** [comment]
Where does `time_taken` come from?  Elda doesn't do json logging. I can't find any reference to that it the source code for Elda or the configuration for `hmlr_elda`.

If this is a generic tomcat thing then it may be outside our control.

**Comment by andrew-pickin-epi** [comment]
Fixed here. 
[epimorphics/master-ansible-deployment edcf43b6f0bc990854ebba51e3b21b842db50d3b](https://github.com/epimorphics/master-ansible-deployment/commit/edcf43b6f0bc990854ebba51e3b21b842db50d3b)
