### ISSUE TITLE
Standard Reports logging

### ISSUE THREAD

**Issue by andrew-pickin-epi** [epimorphics/hmlr-linked-data#113]
- [x] `request-id`
- [x] `status` and `duration`
- [x] Combine request and response events.

1. Standard Reports is logging `request-id` as an increasing (5 digit ?) integer. `request-id` is intended to be the correlating field of the request-id generated be the proxy.

2. In the response message, eg: Response [12499] : 200 (1 ms), the fields `status` and `duration` (integer microseconds) are used elsewhere, consistency would be appecieated.

3. The request and response log events should be combined.

**Comment by der** [comment]
> Standard Reports is logging request-id as an increasing (5 digit ?) integer. request-id is intended to be the correlating field of the request-id generated be the proxy.

The current code uses the value of the header `X-Request-ID` if available, other falls back on it's internal request counter. That's all that can be done by the manager.

**Comment by der** [comment]
Noting that request ID values are coming through in the logs e.g.:

```
Nov 21, 2022 @ 18:32:33.295 | Y3vEQXLEabiRGDp1l-WX4wAAAGY
```

but I suspect they are generated by the data server proxy and not from the pres server proxy.

**Comment by der** [comment]
* Renamed messages from the report processing to use `Report` instead of `Request` to avoid ambiguity with the logging of http requests.
* Added `status` and `duration` to http request logs, renamed `request_id` to `request-id` to match this ticket
* Removed initial request part of http request logs just showing one line per event. Not sure this is a good idea. We've historically found the need to record when a request was received, separately from completion of processing, but going with this for now.
* Added `duration` and `request-id` to report processing logs (note that the id of a report is defined by it's key, e.g. `avgPrice-pcSector-BS35_1-by-none-new-2022-Q1` and is not associated with any specific http request)

Believe this is now complete.

**Comment by der** [comment]
Updated `duration` to pretend to be microseconds instead of ms.

This release is now version 0.1.1

**Comment by andrew-pickin-epi** [comment]
The request-id is being used for the carry the name of the report as in this example:
```
{"ts":"2022-11-25T12:25:08.444Z","version":"1","message":"Processing report: banded-pcDistrict-BS34-by-pcSector-old-2021-Q3","logger_name":"com.epimorphics.standardReports.ReportManager","thread_name":"pool-1-thread-1","level":"INFO","level_value":20000,"request-id":"banded-pcDistrict-BS34-by-pcSector-old-2021-Q3"}
```
Request this is changed to `report-id` and the `request-id` be the one generated from the proxy so that reconsiliation can be done.
The request-id (in either form is missing from some logging. Eg
```
{"ts":"2022-11-22T08:27:50.908Z","version":"1","message":"Report processor starting","logger_name":"com.epimorphics.standardReports.ReportManager","thread_name":"pool-1-thread-1","level":"INFO","level_value":20000}
```

Can there also be included a state field to display the processing of any report request rather than it needing to be worked out from the contents of the text message. Suggest something like Accepted/Processing/Complete to indicate the original receipt, construction and completion of the report.

**Comment by der** [comment]
> The request-id (in either form is missing from some logging. Eg

Correct, that has no associated request and so no request ID.

**Comment by andrew-pickin-epi** [comment]
So what is 
```
{"ts":"2022-11-22T08:27:50.908Z","version":"1","message":"Report processor starting","logger_name":"com.epimorphics.standardReports.ReportManager","thread_name":"pool-1-thread-1","level":"INFO","level_value":20000}
```
telling me? Is this the container starting? If so it could be worded better.

**Comment by der** [comment]
> So what is

{"ts":"2022-11-22T08:27:50.908Z","version":"1","message":"Report processor starting","logger_name":"com.epimorphics.standardReports.ReportManager","thread_name":"pool-1-thread-1","level":"INFO","level_value":20000}
> telling me? Is this the container starting? If so it could be worded better.

No. The ReportManager is a class within the container and that is telling me that the thread that processes reports has started. If there's some succinct but better phrasing for that, one which I can understand, then feel free to suggest it.

> Also this one:
{"ts":"2022-11-01T10:00:04.307Z","version":"1","message":"Response [49] : 200 (3 ms)","logger_name":"com.epimorphics.standardReports.webapi.LogRequestFilter","thread_name":"http-nio-8080-exec-10","level":"INFO","level_value":20000,"path":"/sr-manager/system/status","request_id":"49"}
> What is this a Response to?

It is a request which doesn't have an original x-Request-Id so the logger has had to fall back on the internal request count as the only thing it has. What else could it do? Looks like a health check ping that is going direct to the container. Which seems reasonable. 

> When viewed alongside

{"ts":"2022-10-27T15:47:53.309Z","version":"1","message":"Response [Y1qoKSzNASZH5E8lgyYiMQAAAJA] : 200 (29 ms)","logger_name":"com.epimorphics.standardReports.webapi.LogRequestFilter","thread_name":"http-nio-8080-exec-3","level":"INFO","level_value":20000,"path":"/sr-manager/report-request/avgPrice-pcSector-W2_2-by-none-old-2022","request_id":"Y1qoKSzNASZH5E8lgyYiMQAAAJA"}

> The request-id doesn't look completely happy, and status and duration not consistent either.

Looks like this is old version of the container all uses of `request_id` (which is what we had before) should have been changed to `request-id` to match your request on this ticket.

If it really is the current version then I can take a look.

**Comment by der** [comment]
And indeed checking on the actual running container see just `request-id` not `request_id` and do see `status` and `udration` values. The date stamps for all except the first example look to be before all the changes,

**Comment by andrew-pickin-epi** [comment]
All the messages quoted say `"version": "1"`
This one is from today and has the report name in `request-id`.
```
{"ts":"2022-11-25T12:25:33.926Z","version":"1","message":"Report completed: banded-pcDistrict-BS34-by-pcSector-old-2021-Q4 in 1.174 s","logger_name":"com.epimorphics.standardReports.ReportManager","thread_name":"pool-1-thread-1","level":"INFO","level_value":20000,"request-id":"banded-pcDistrict-BS34-by-pcSector-old-2021-Q4","duration":"1174000"}
```

**Comment by der** [comment]
> All the messages quoted say "version": "1"

That's a different question.

Version isn't something we explicitly set, I believe it indicates the version of the LogStashEncoding format (which is what we are using to get json) is being offered. I can probably remove that if it would avoid confusion since we are not actually compliant with LogStash anyway (e.g. renamed `timestamp` to `ts`).

> This one is from today and has the report name in request-id.
> {"ts":"2022-11-25T12:25:33.926Z","version":"1","message":"Report completed: banded-pcDistrict-BS34-by-pcSector-old-2021-Q4 in 1.174 s","logger_name":"com.epimorphics.standardReports.ReportManager","thread_name":"pool-1-thread-1","level":"INFO","level_value":20000,"request-id":"banded-pcDistrict-BS34-by-pcSector-old-2021-Q4","duration":"1174000"}

Yes, that's the intention, see earlier discussion. Already said that if you are sure you want this changed then can do that.

Apart from that change are they any other anomalies from after the update (2022-11-22) that need to be looked at?

**Comment by andrew-pickin-epi** [comment]
It's a bad precident to change the meaning of a field between log events. 
It becomes problematic to correlate the request with the report if the `request-id` is surplanted by the report name.
So keep the `request-id` as the `x-request-id` header as the correlation item and a new field as some variation of `report`/ `report_name`/`report_id`. A processing state field would be nice so we don't have to regexp the message text.

**Comment by der** [comment]
OK. Switched to using `report-id` for the report backend processing and added a `state` field which is one of:

* `Accepted`
* `Processed`
* `Completed`
* `Error`
