### ISSUE TITLE
Set cache control headers for HMLR apps

### ISSUE THREAD

**Issue by der** [epimorphics/hmlr-linked-data#114]
Set `public` rather than `private` and set non-zero `max-age`.

For `ppd` and `landing` a `max-age` of 300 is probably right.

For `ukhpi` needs to be shorter to avoid delay (in users cache) on the publication deadline maybe 120?

**Comment by jonrandahl** [comment]
@der 

I'm highlighting the caching settings on the RegProd `environments/production.rb` file[^1] and also wanted to point out that Rails provides different stores for the cached data (apart from SQL and page caching).[^2]

```ruby
# frozen_string_literal: true

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Code is not reloaded between requests.
  config.cache_classes = true

  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = true

  # Full error reports are disabled and caching is turned on.
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true

[ ... ]

  # Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?

[ ... ]

  # Use a different cache store in production.
  # config.cache_store = :mem_cache_store <-- Only pointing this out for reference, see FN2

[ ... ]

  # This will affect assets served from /app/assets
  config.static_cache_control = "public, max-age=#{5.minutes.to_i}"

  # This will affect assets in /public, e.g. webpacker assets.
  config.public_file_server.headers = {
    'Cache-Control' => "public, max-age=#{5.minutes.to_i}",
    'Expires' => 5.minutes.from_now.to_formatted_s(:rfc822)
  }

[ ... ]

end
```

Also, @joescottdave pointed out today that some of the LR apps are currently on v5 of Rails and should be updated all things considered, he also mentioned that he's read somewhere that moving jumping to v7 is sometimes easier than going from v5 > v6 > v7 sequentially. I've asked for references so I can evaluate the process as well so that's something to think about.

[^1]: Omitted code available on the [original](https://github.com/epimorphics/regulated-products-app/blob/main/config/environments/production.rb)
[^2]: https://guides.rubyonrails.org/caching_with_rails.html#connection-pool-options

**Comment by der** [comment]
Thanks @jonrandahl . From my point of view we only care about the cache control headers, so those last two blocks. Caching the fully rendered pages after the API calls I think can be useful. Whereas internal rails caching I think is not needed unless we have a specific bottleneck that we can measure and improve on. Good to know though.

In terms of rails versions my understanding was that we're limited to v5 by qonsole and so `landing` at least needs to stay v5. If the other apps can be safely upgraded with low cost and minimal risk then great. If it proves to be a tar pit then we could consider decoupling the rails upgrade and doing that at our leisure, it doesn't feel as burning an issue as the obsolete infrastructure :sweat:

**Comment by jonrandahl** [comment]
I've now added the required 300 second expiry configurations to each of the apps

```ruby
  # * Set cache control headers for HMLR apps to be public and cacheable
  # * Standard Reports uses a time limit of 5 minutes (300 seconds)
  # This will affect assets served from /app/assets
  config.static_cache_control = "public, max-age=#{5.minutes.to_i}"

  # This will affect assets in /public, e.g. webpacker assets.
  config.public_file_server.headers = {
    'Cache-Control' => "public, max-age=#{5.minutes.to_i}",
    'Expires' => 5.minutes.from_now.to_formatted_s(:rfc822)
  }
```

 while refactoring the UKHPI TTL to be 120 seconds as requested:

```ruby
  # * Set cache control headers for HMLR apps to be public and cacheable
  # * UHPI needs to be shorter to avoid delay (in users cache) on the
  # * publication deadline so it is set for 2 minutes (120 seconds)
  # This will affect assets served from /app/assets
  config.static_cache_control = "public, max-age=#{2.minutes.to_i}"

  # This will affect assets in /public, e.g. webpacker assets.
  config.public_file_server.headers = {
    'Cache-Control' => "public, max-age=#{2.minutes.to_i}",
    'Expires' => 2.minutes.from_now.to_formatted_s(:rfc822)
  }
```

The updates have been branched from the respective `dev-infrastructure` branch of each app to then be implemented on the new lift & shift instances once they've gone up the stack.

**Comment by der** [comment]
This is not working. E.g.

```
$ curl -I https://hmlr-dev-pres.epimorphics.net/app/ppd/
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate, max-age=3600
```

Same for ukhpi.

However, at this point I don't think it's worth more struggling with this. It's this way in production and probably marginal benefit.

So propose to close.

**Comment by tomguilbert** [comment]
@jonrandahl still needs to add the default caching policy into the application controllers

**Comment by jonrandahl** [comment]
Following the release of the application controller updates this has now resulted in the following results from the command line:

### `curl -I https://hmlr-dev-pres.epimorphics.net`

```sh

HTTP/1.1 200 OK
Cache-Control: max-age=300, public, must-revalidate, max-age=3600
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jul 2023 15:02:57 GMT
ETag: W/"350bef6ee4648b1bf4d9c0f4cb920363"
Expires: Tue, 11 Jul 2023 16:02:57 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: Apache
Set-Cookie: _lr-landing_session=RE1jZnN3cmxmSTYvT1RLc2N4UDh5M1cySFNwcW1PelE3S1JrYkExblZxY3Bjd1huYXZXaWg1d1Fxdmc0RWsrY0ZTRjFtdzN0MHVIb0xtYWxEZytXT2p4Q1gyWmJ0V1NsdzNmWkNoVXhaM1YvdzNNMVphMk9kbzlLYUs4Tk1pR1BKVGU3SE1hWDZORU04UUZWTFZ3Z0hBPT0tLVRxNytjb1ZEa2thSW5aMC9VUzFqVWc9PQ%3D%3D--51898325207819a32d1827f7776c7149e9f15043; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: ZK1vIVG4D1IXuHDpKp4GiAAAAAY
X-Runtime: 0.004237
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

### `curl -I https://hmlr-dev-pres.epimorphics.net/app/ppd/`

```sh
HTTP/1.1 200 OK
Cache-Control: max-age=300, public, must-revalidate, max-age=3600
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jul 2023 15:05:54 GMT
ETag: W/"583c7e1c1f0e8af043f9badacd151bc5"
Expires: Tue, 11 Jul 2023 16:05:54 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: Apache
Set-Cookie: _ppd-explorer_session=TjZhWmEreDY5cS93amJBWFppMHYwNE0rdk5TSnNKNWorSWhpRDlPYjFjWjBWeHoyb2htVjgrR0l5amtvQ05ZVTF4bDF2SXFVRVh0MXZVeUpRWlNjOUtLZ1lUK2k5V2JNWXRjUEpCSy9ZRUEwRWV6bTFOUEZtZjB3d090SkM1RjEvcnpIVTJOTlZTZG50MjlXMFViek9oZnBYTVVoVlNiR1V4bVdkWWVTQnQrMllBQWFjZHc4azkyTG16eXo2WUlnLS13WGF1MVN5d1hQSE5meUZQYVFIZE9RPT0%3D--70c77f5f56e56007475c27c08122718228475151; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: ZK1v0kroMdHvazsGsxS25wAAAOk
X-Runtime: 0.004949
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

### `curl -I https://hmlr-dev-pres.epimorphics.net/app/standard-reports/`

```sh
HTTP/1.1 200 OK
Cache-Control: max-age=300, public, must-revalidate, max-age=3600
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jul 2023 15:06:51 GMT
ETag: W/"affe53d4d7822aa26169d42b7a1dc5aa"
Expires: Tue, 11 Jul 2023 16:06:51 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: Apache
Set-Cookie: _standard-reports-ui_session=eUFHN3lxUGtnYmZ2RExiL3laYXRUUGFlUDhNbVAxeGVvTGdZeEl2SG9URXpaSXNhS20zd1FOSHAyaU1DcUhBYktMUkN0ZHBGWW5KUTJkcHlBbWNZN1prYmJnQUEyZHBEV00xTHFwM1NiK0Z1K2t2RkVMVDN0RUl6RTR5My9BeXJ2TG5VQnMxc0dBZUQ2TzY5V21JNWl3PT0tLWtkOUZZaCtZODU3dEVmZUZiZjl2K0E9PQ%3D%3D--b66f33e0f8f90dcb9cbb5422b264d6b47e176dfb; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: ZK1wC0roMdHvazsGsxS3CQAAAPk
X-Runtime: 0.041196
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

### `curl -I https://hmlr-dev-pres.epimorphics.net/app/ukhpi/`

```sh
HTTP/1.1 200 OK
Cache-Control: max-age=120, public, must-revalidate, max-age=3600
Content-Security-Policy: script-src 'self' https: 'unsafe-inline' 'unsafe-eval'
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jul 2023 15:07:38 GMT
ETag: W/"667dcaffb17fad0092d865134636fdbb"
Expires: Tue, 11 Jul 2023 16:07:38 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: Apache
Set-Cookie: _ukhpi_session=yzbOie%2B2XdBtbu24FSeX1yTO9XVkXEU41KgF%2FqqUULsD90cmTtrF8SRbdYibcMyy2DNTC4o5Ap0i4yCLkGuzqL07SpHBE3q3%2BxG09ZVWHASbAfFfSbKO0qMBVwxkyBiFQD7IWC7ELIPYRY2dw0POiAy%2BC0%2FGA8341RT9rgH4OVmHrd9R2IrwkY%2FVC6T4Z%2BFOkuSq0ErXkdHxHpABOnHiOGt1zWm%2BgBzfg8BB%2Fc%2BTTel0S31CMa68pugXDBbqy%2BoV3P1%2FPHifzypKrqOc95DxDKKMfX2BzA%3D%3D--IRCLGRMgIsvJ3%2FL%2B--W%2BecNbBX4Yj%2FRt%2B29Xcpsg%3D%3D; path=/; HttpOnly
Vary: Accept,Accept-Encoding
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: ZK1wOkroMdHvazsGsxS3JQAAAPY
X-Runtime: 0.048690
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

Hopefully this resolves this ticket @tomguilbert . 😄

**Comment by tomguilbert** [comment]
Thanks @jonrandahl - as before I will need someone who can speak log to confirm one way or the other

**Comment by jonrandahl** [comment]
@der I've had a look at the manner of which the headers are being set in the code and cannot see the `max-age` being set twice. I've also looked at the app's response headers which show the cache control being the 300s set by the new code I've added:
![CleanShot 2023-07-17 at 11 27 21](https://github.com/epimorphics/hmlr-linked-data/assets/39102/721623bd-7c35-454f-9550-1ae7faf76d08)
Therefore, I am pretty sure this might be something from the proxy or elsewhere being added?
Hope this helps!

**Comment by der** [comment]
This relates to https://github.com/epimorphics/hmlr-ansible-deployment/issues/159 which showed that caching was not happening.

Closing 159 and resolve here.

**Comment by der** [comment]
Confirmed that the second `max-age` setting (of 3600) was coming from the proxy configuration. 

It turns out that apache's `ExpireDefault` will only respect an `Expires` header from the origin service, not a `cache-control: max-age`. Removed use of `ExpireDefault` has removed the extra `max-age`.

Though server side disk caching is still not actually functional ...

**Comment by der** [comment]
Cache was not enabled for the apps, added for ukhpi and ppd.
