### ISSUE TITLE
SPARQL form randomly switches to Welsh

### ISSUE THREAD

**Issue by der** [epimorphics/hmlr-linked-data#131]
View UKHPI main page (in English), refresh, select `SPARQL Query` some of the time (maybe 50% on average) the Sparql form will come up with the header bar in Welsh.

Not seen this happen production at all.

**Comment by jonrandahl** [comment]
This has proven to be more difficult to resolve as the lang query parameter is not being honoured all the time even though it's present in the URL. 

For the record, this issue has also been highlighted on #119 while the resolution needs further investigation to determine why the lang param is being ignored

**Comment by tomguilbert** [comment]
Jon and I have tried to reproduce this but can't so suggest we close if that's alright @der? #119 is still an issue, but as that suggests, not a regression so leave for now.

**Comment by der** [comment]
Fine to close.
