### ISSUE TITLE
Investigate starting date range configuration

### ISSUE THREAD

**Issue by jonrandahl** [epimorphics/hmlr-linked-data#134]
As reported by @der:

> The oddity is the starting date range for UKHPI. It seems to working for me in prod and not production (!). It has always been a little strange but might be worth a brief investigation into how it's supposed to work and whether there's an issue there

**Comment by der** [comment]
For example, for me if I navigate to the production LR site [UK HPI](https://landregistry.data.gov.uk/app/ukhpi) and then `search the UK house price index` I get:

![ukhpi](https://github.com/epimorphics/hmlr-linked-data/assets/805075/89481c36-ecb6-43ef-8ad7-ad981f465a4f)

This shows the range August to August. The URL in the search bar includes the from/to query parameters that match the display.

Yet the current data goes up to the end of September and if I explicitly change the search range I can see that. If I navigate away then come back in a new tab or in-cognito I'm back to and Aug to Aug view.

I'm not sure how the data range to display is worked out but it's not working for me.

Whereas, at least for me, the [dev service](https://hmlr-dev-pres.epimorphics.net/app/ukhpi/) shows Oct to Oct which is what I would expect.

**Comment by jonrandahl** [comment]
@der after ticket gardening with @tomguilbert I've checked the dev/preprod/prod instances and all seem to be displaying the same expected date range: Sept 2023 ~ Sept 2024 [^1][^2][^3]

Is this still an issue?

[^1]: https://hmlr-dev-pres.epimorphics.net/app/ukhpi/browse?from=2023-09-01&location=http%3A%2F%2Flandregistry.data.gov.uk%2Fid%2Fregion%2Funited-kingdom&to=2024-09-01&lang=en
[^2]: https://hmlr-preprod-pres.epimorphics.net/app/ukhpi/browse?from=2023-09-01&location=http%3A%2F%2Flandregistry.data.gov.uk%2Fid%2Fregion%2Funited-kingdom&to=2024-09-01&lang=en
[^3]: https://landregistry.data.gov.uk/app/ukhpi/browse?from=2023-09-01&location=http%3A%2F%2Flandregistry.data.gov.uk%2Fid%2Fregion%2Funited-kingdom&to=2024-09-01&lang=en

**Comment by der** [comment]
Yes, unable to reproduce earlier problem so fine to close.
