### ISSUE TITLE
Missing detailed ppd documentation

### ISSUE THREAD

**Issue by der** [epimorphics/hmlr-linked-data#145]
The landing page has a link under Price Paid Data > Further Information > detailed documentation.

In the legacy service this links to: `/app/root/doc/ppd` see http://lr-ppd-production-pres-1.epimorphics.net/app/root/doc/ppd

In the new service it links to `/doc/ppd` (which ends up at Elda) and the expected link `/app/root/doc/ppd` does 404s

**Comment by andrew-pickin-epi** [comment]
`/app/root/doc/ppd` is not "expected". 
We should just have a redirect for this legacy address as per the `/ppd-documentation.html` 
I've added this into the proxy config and confirmed it's working.
