### ISSUE TITLE
LR Sapi Endpoint

### ISSUE THREAD

**Issue by bogdanadrianmarc** [epimorphics/hmlr-linked-data#19]
When previously testing out the changes I made to the DSAPI gem, I used a local SAPINT API. In order for that change to work when the apps are deployed we need a URL which points to a running SAPINT API. I remember we needed to set a hard limit of 100 (I think) to avoid crashing the API with the testing, so this needs to be removed as well. Also, the explain feature is still on a separate branch, we need to either create the API using that branch or merge that into main

@mika018 I tried assigning you to this but I'm not able to assign on the repo 🤔

**Comment by mika018** [comment]
I don't have the exact URL for the API but if you make that configurable through an environment variable then I will be able to set it when I do the deployment. 

I have merged the explain controller to master on the `lr-data-api`

**Comment by ijdickinson** [comment]
Dev API notes have been added to the readme
