### ISSUE TITLE
Cookie banner not in Welsh

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/hmlr-linked-data#27]
On the [Welsh language landing page](https://lr-preprod.epimorphics.net/app/root/?lang=cy), the cookie notice is shown in English:

![image](https://user-images.githubusercontent.com/63979/123663685-8ec06200-d82e-11eb-96b7-f4b4fa9f2326.png)

**Comment by ijdickinson** [comment]
Also, I thought there would be a link to the new policy page in the banner?

**Comment by joescottdave** [comment]
This is the yet to be deployed changes

**Comment by ijdickinson** [comment]
Ah, sorry. I thought we were up-to-date. My mistake
