### ISSUE TITLE
UKHPI readme tweaks

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/hmlr-linked-data#51]
Following up on the 2021 update of the UK location boundaries, we should make a few changes to the `readme` that captures the process.

Some of the things to add (there might be others that I have forgotten!):

Dev tasks - document the following:
- [ ] installing the Jena Fuseki command line tools, and setting the `FUSEKI` env variable
- [ ] when using `preprod` for QA, for the linked data API we can actually create an ssh tunnel directly to the back-end data server Fuseki
- [ ] where to put the GeoJSON file
- [ ] what to expect as resulting code diffs (for sanity checking)
- [ ] manual QA steps

Acceptance criteria
- You can run through the instructions with dummy data and complete the creation of new geographies

Estimate
2 days , 1 to write, 1 to test

We should also make a note to review all of this again in the light of the new infrastructure.

**Comment by mairead** [comment]
see notes in #50

**Comment by ijdickinson** [comment]
done
