### ISSUE TITLE
LR landing repo has an out-of-date readme

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/hmlr-linked-data#53]
@andrew-pickin-epi wrote:

> The Readme even in the dev-infrastructure branch still makes reference to Chef.

> I would also expect a description of the interface this provides, or link to same elsewhere.
> For example the environment variables it uses/requires and what they represent.
> The expected endpoints of application/requirements in configuring any proxy, metrics or 
> health checks to assit in configuring monitoring.

**Comment by ijdickinson** [comment]
Having looked at this, the core of the README is OK. The deployment section is out-of-date, but updating the README is blocked by ticket #54 (adopt the standard pattern for container deployments)

**Comment by mairead** [comment]
Will handle this as part of 53
