### ISSUE TITLE
Landing: Full market Value label change

### ISSUE THREAD

**Issue by mairead** [epimorphics/hmlr-linked-data#59]
Edit
“Can you please ask Epimorphics to change 'full market value' to 'value' in the following sentence under the 'Transactions' heading:

"A standard PPD transaction concerns a single residential property sold for full market value to private individual."

The URL is
https://landregistry.data.gov.uk/app/root/doc/ppd

Change is found in the landing application

Acceptance criteria
- Text is updated

Estimate
0.5

**Comment by ijdickinson** [comment]
Also merged into `dev-infrastructure`

**Comment by ijdickinson** [comment]
Additional request from client to add emphasised copy:

> From October 2015 we have added a new category of price paid data known as additional price paid data. 
> This new data, captured since 14 October 2013, includes data about:
>    property transfers carried out under a power of sale  repossessions
>    buy-to-lets where they can be identified by a mortgage
>    transfers to non-private individuals
>    **sales where the property type is classed as ‘Other’**

**Comment by ijdickinson** [comment]
Done
