### ISSUE TITLE
Query count not rendering (ppd-explorer)

### ISSUE THREAD

**Issue by joescottdave** [epimorphics/hmlr-linked-data#70]
See issue #63 
Also missing in #64 

Query count is not rendering. Where results are capped at 100 or 1000 the string of text that displays total number of matching transactions is not rendering its numerical value.

Expected:
![image](https://user-images.githubusercontent.com/15012420/147086520-b0b25ac1-d541-4811-a6f7-5e946ff9d407.png)

Received:
![image](https://user-images.githubusercontent.com/15012420/147086526-5c3b0aa6-1fe9-4c55-80b7-84a36b04085b.png)

**Comment by joescottdave** [comment]
Possible regression in Data Services API? @bogdanadrianmarc @ijdickinson 

PPD tries to unpack the response with this code `count = count_result.first['@count']` but we're seeing this return `nil`

```
[{"ppd:count"=>9834}]
(byebug) count_result.first['@count']
nil
(byebug) count_result
[{"ppd:count"=>9834}]
(byebug) count_result.first['ppd:count']
9834
```

**Comment by ijdickinson** [comment]
This is now working correctly on the dev service
