### ISSUE TITLE
Locality field not available in search form in dev-infrastructure

### ISSUE THREAD

**Issue by mairead** [epimorphics/hmlr-linked-data#71]
http://hmlr-dev-pres.epimorphics.net/app/ppd/

Suspect PPD explorer needs to be updated from the version currently in main dev branch because we added a locality field a couple of months ago and its missing in the dev-infrastructure branch. It probably just needs updated from dev branch to make sure there aren't any other code changes missing

**Comment by ijdickinson** [comment]
Fixed
