### ISSUE TITLE
Number of properties found differs when searching for county: 'devon'

### ISSUE THREAD

**Issue by mairead** [epimorphics/hmlr-linked-data#72]
See #64 

I expected to find the result 'Summary will display '57 properties' when searching for County: 'devon' and instead I found 58

I'm not sure if this a result of data inconsistencies or an actual error in the code

**Comment by ijdickinson** [comment]
Seems to have been fixed by either the recent API change, or the update to ensure that the data on production and dev are the same. Either way, `hmlr-dev-pres` and production now produce the same results.
