### ISSUE TITLE
Number of properties & address of first differs when searching all for Building name or number: 'Rose cottage'

### ISSUE THREAD

**Issue by mairead** [epimorphics/hmlr-linked-data#73]
See #64 

- I expected 'Rose Cottage, Lower Gustard Wood, St Albans, AL4 8RU' and received Rose Cottage, Warbage Lane, Bromsgrove, B61 9BL
- I expected 'Summary will display '5887 properties'' and received '296 properties'
- I expected the warning phrase ''We have limited this page to 5000 results'' to appear and it did not

We could not replicate the large queries test either, because the full dataset does not appear to be available

**Comment by ijdickinson** [comment]
Initial working hypothesis is not that this is because of a shortage of source data, but more likely a query limit being applied in the API

**Comment by mika018** [comment]
A soft limit of 500 on both the ppd and the ukhpi endpoints have been removed
epimorphics/lr-data-api@444cde3

**Comment by ijdickinson** [comment]
With the soft limit removed, we see more similar results from production and dev. But not the same. Next action is to ensure that the data on dev is identical to production. After that, we will investigate details of the SPARQL queries to see if there are differences that could account for the discrepancies

**Comment by ijdickinson** [comment]
Having updated the the data on dev to match production (thanks @der ), I have not been able to find any combinations of PPD search terms where the results on dev differ from the results on production.

I'm also not sure that the QA test is quite right. There are three conditions on the search form: max 100 results, max 1000 results, and all results. On production (as of Jan 2021), the results on production are:

- max 100 gives 100 transactions for 62 properties
- max 1000 gives 1000 transactions for 568 properties
- no limit gives 9933 transactions for 5918 properties

I am seeing the same results from the QA test service, so I am satisfied that the QA test service is functioning correctly.
