### ISSUE TITLE
Incorrect 404 page for PPD

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/hmlr-linked-data#77]
PPD is not showing the correct 404 page for non-recognised URLs. For example, http://hmlr-dev-pres.epimorphics.net/app/ppd/FOOBAR:

![Screenshot from 2022-01-13 16-04-16](https://user-images.githubusercontent.com/63979/149365758-928be908-8ba3-4e82-a7c8-55dbfe11879f.png)

**Comment by andrew-pickin-epi** [comment]
I don't see the above, I see a LR page. But it appears to be missing a `landing.css` & the OGL logo.

**Comment by jonrandahl** [comment]
closing as this is most definitely resolved:
![CleanShot 2023-07-04 at 17 11 22](https://github.com/epimorphics/hmlr-linked-data/assets/39102/9ba7c838-4b7f-49a9-851b-12ce34ee9a25)
