### ISSUE TITLE
Log details of requests to data API

### ISSUE THREAD

**Issue by andrew-pickin-epi** [epimorphics/hmlr-linked-data#85]
PPD logs are light on detail when performing calls to data-api:

Consider:
```
{"level":"INFO","ts":"2022-01-24T15:10:24.379Z","request_id":"Ye7BV0R3bsaE5OQrLPQY9gAAAAA","rails":{"environment":"production","format":"html","controller":"SearchController","action":"create","view":243.74,"exception":null,"exception_object":null},"method":"POST","path":"/app/ppd/search","status":200,"duration":9360.43}
```
There is no body data logged with this request.
There is no record of the call to data-api. 
The status returned by data-api, number of rows, data size, upstream duration, etc is omitted from any logs.
It is very difficult to reconcile this log entry with any search operations other than comparing timestamps.

**Comment by ijdickinson** [comment]
> There is no body data logged with this request.

Are you sure you want this? The body data from one data API call could be multiple megabytes

**Comment by andrew-pickin-epi** [comment]
I think we need sometime logged that describes what we are searching for. 
For example I'm expecting something that say "Rose Cottage"

**Comment by ijdickinson** [comment]
> I think we need sometime logged that describes what we are searching for.

OK. At the moment, we delegate logging of API calls to the library (Faraday) that we use to make the HTTP interaction. I'll see if it's possible to customise its behaviour

**Comment by ijdickinson** [comment]
Since this will be generic to all of the applications, I've updated the title to remove the reference to PPD. We can test the fix in PPD, but the behaviour should be consistent for all of the HMLR apps

**Comment by ijdickinson** [comment]
POSTing to the remote data API is a feature of the old DsAPI. Now that we are using SapiNT, API requests are only made as GET requests, and the URL of the call is recorded in the log. So logging the body of the request is no longer relevant.

I am currently looking at a change that will associate the GET URL with the response code and duration in the log

**Comment by ijdickinson** [comment]
done
