### ISSUE TITLE
Customer issue: Standard reports - issue running Regions 2020 data

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/hmlr-linked-data#90]
Via Sue Gambles, a report of an issue experienced by a customer:

> I have attempted to download data from the HM Land Registry website and have run into some difficulties. The data I am looking to download has the following characteristics:

> Report type – average prices and volumes
> Area Type – Country
> Country – England & Wales
> Aggregate Data – Region
> Dates – 2020
> Age of property – Any.

> And when I click generate report, it says “in progress, estimated complete in less than 5 seconds” and stays on that without any report being generated. I have changed the Dates to 2021 and 2019 and reports have been generated, however I still seem to have an issue for the 2020 data. I’m not sure whether this is an issue for other people, but I thought I’d let you know.

Sue says that she has also tried the same settings, and did not get a report.

**Comment by der** [comment]
Inspecting the `production-Queue` table in Dynamo DB there were five items, including that one, that were marked as `inprogress` but very out of date and clearly no long in progress. Possibly a result of a past server restart while some Standard Reports were running.

Deleted the stale queue entries and ran the same report via the UI again. Report completed safely.
