### ISSUE TITLE
UK HPI & Std Reps UI incomplete metrics.

### ISSUE THREAD

**Issue by andrew-pickin-epi** [epimorphics/hmlr-linked-data#97]
UK HPI & Std Rep UI images currently in dev have incomplete metrics.
```
  std_rpts_ui: 1.4.0-54d8db2
  ukhpi: 1.6.0-f822314
```
eg memory usage guage has no value. 

Note this was the case with ppd, but was one of the last issues fixed by Ian.

**Comment by andrew-pickin-epi** [comment]
Ruby dashboard is not in place. When application metrics in place they should appear [here](https://grafana-hmlr.epimorphics.net/d/RubyApp/ruby-application?orgId=1&var-application=ukhpi&from=now-1h&to=now&refresh=10s).

**Comment by tomguilbert** [comment]
PPD is working as expected, but UKHPI and SR are returning values of `0` and Landing has no data (null)

**Comment by jonrandahl** [comment]
@andrew-pickin-epi you state:

> Note this was the case with ppd, but was one of the last issues fixed by Ian.

Expectedly I'm having a hard time working out what specific changes these were? 

Funny enough I wondered if [Ian's last release](https://github.com/epimorphics/ppd-explorer/blob/dev-infrastructure/CHANGELOG.md#170---2022-04-07) might be the one but was unable to verify...  

I would like to point out that I've looked at all of the prometheus metrics and they're the same for each HMLR application so any further evidence of the desired changes mentioned would be greatly appreciated! 🙏

**Comment by andrew-pickin-epi** [comment]
According to the change log 1.6.0 & 1.6.1.

**Comment by jonrandahl** [comment]
Use this commit for reference: https://github.com/epimorphics/ppd-explorer/commit/cd1ae1e6a58183ca596faef362b780d8138c8cba

**Comment by andrew-pickin-epi** [comment]
See end of this commit, looks most likely.

https://github.com/epimorphics/ppd-explorer/commit/cd1ae1e6a58183ca596faef362b780d8138c8cba

**Comment by tomguilbert** [comment]
@andrew-pickin-epi - Jon and I have been discussing this and he reckons this can be closed because:

* Standard Reports has https://grafana-hmlr.epimorphics.net/d/RubyApp/ruby-application?orgId=1&var-application=std-rpts-ui&var-env=prod&var-host=hmlr-blue-pres-171&var-instance=10.10.10.171:3003
* UKHPI has https://grafana-hmlr.epimorphics.net/d/RubyApp/ruby-application?orgId=1&var-application=ukhpi&var-env=prod&var-host=hmlr-blue-pres-171&var-instance=10.10.10.171:3002

Is that OK?

**Comment by andrew-pickin-epi** [comment]
can be closed
